# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RajaTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RajaTalk
  pod 'IQKeyboardManager'
  pod 'BEMCheckBox'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'ContactsWrapper', '1.0.2'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
